[devshell]
packages = [ "julia_16-bin" ]

[[commands]]
name = "pluto"
category = "Julia"
command = '''
        eval $(echo "julia -e 'import Pkg; Pkg.activate(\".\"); using Pluto; Pluto.run()'")
        '''
help = "launch pluto server"

[[env]]
name = "JULIA_DEPOT_PATH"
value = "./.julia_depot"

[[env]]
name = "JULIA_PROJECT"
value = "."
